version: "3.8"
services:
    database:
        image: postgres:13.5
        restart: always
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=notaros
        volumes:
            - database:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - database
        ports:
            - "8080:8080"
        volumes:
            - ./:/app

volumes:
    database:
    app:
